name: lkc
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.3
  flutter_localizations:
      sdk: flutter
  http: ^0.12.0+1
  shared_preferences: ^0.5.1+2
  #rflutter_alert: ^1.0.2
  rich_alert: ^0.1.32
  draggable_flutter_list: ^1.0.3
  #intro_views_flutter: ^2.4.0
  #intro_slider: ^1.1.9
  #fancy_bottom_navigation: ^0.3.2
  curved_navigation_bar: ^0.1.26
  giffy_dialog: ^1.3.0
  flutter_svg: "^0.5.0"
  spinner_input: ^0.1.1
  dropdown_formfield: ^0.1.0
  smooth_star_rating: 1.0.2
  introduction_screen: ^1.0.0
  fluttertoast: ^2.1.4



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
   uses-material-design: true

  # To add assets to your application, add an assets section, like this:
   assets:
    - images/wallpaper.jpg
    - images/translation_logo.png
    - images/gloss_translation_logo.png
    - images/gloss_modification_logo.png
    - images/sort_logo.png
    - images/woman_avatar.png
    - images/participation.png
    - images/gloss_sort_logo.png
    - images/modification_logo.png
    - images/validation_logo.png
    - images/guide.png
    - images/profile.jpg
    - images/localization.png
    - images/ont_localization.png
    - images/ss_task.jpg
    - images/ss_domain.jpg
    - images/ss_translation.jpg
    - images/gap_translation.jpg
    - images/prev_translation.jpg
    - images/ss_mod.jpg
    - images/ss_valid.jpg
    - images/ontology.png
    - images/lkc.png
    - images/china.png
    - images/france.png
    - images/germany.png
    - images/japan.png
    - images/russia.png
    - images/united-kingdom.png
    - assets/locale/localization_en.json
    - assets/locale/localization_mn.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
